<?php 
/**
 * Cronjob Scheduler Include File
 *
 * This page allows you to create Cronjob Scheduler custom actions
 * through the WordPress admin. Actions can also be created within
 * theme files or other PHP files throughout your WordPress install.
 *
 * Do not edit this file unless you have a good understanding of PHP, 
 * saving this with invalid code can render your WordPress install inoperable
 * until you can fix the issue using FTP or another file editing utility.
**/

function my_cronjob_action () {
    // code to execute on cron run
  // if ( file_exists( $_SERVER['DOCUMENT_ROOT'] . '/wordpress/wp-config.php') ) {
  //   // * The config file resides in ABSPATH 
    require_once(  $_SERVER['DOCUMENT_ROOT'] . '/wordpress/wp-config.php'  );
  // // }
  $query="insert into wp_student_details(first_name, last_name, gender, dob, resume_file) values ('Gautam','Moradiya','male','1992-04-22','xyz.jpg')";
  print_r($wpdb);
} add_action('my_cronjob_action', 'my_cronjob_action');

// add_action('admin_menu', 'insert_user_random', 10, 1 )


